const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const D=require('./dungeon-knowledge.js');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name)}
const map={objects:[{id:'gate',type:'entrance',tile:[0,0]},{id:'fountain',type:'fountain',interaction_tiles:[[3,3]]}],doors:[],hazards:[{id:'pit',type:'pit',tile:[1,0],damage:2,destination:{floor:1,tile:[2,0]}}]};
function party(){const s={floor:1,x:0,y:0,dir:1,party:[{hp:20}],visited:{'1:0,0':true}};D.normalize(s,map);return s}
test('Legacy saves preserve exploration and migrate Perception and landmarks',()=>{const s=party();assert.equal(s.party[0].perception,10);assert.equal(s.visited['1:0,0'],true);assert.equal(s.knowledge.landmarks['1:gate'],true)});
test('Low Perception requires directional LOOK; warning happens only once',()=>{const s=party(),logs=[];const opts={clear:()=>true,notify:m=>logs.push(m)};assert.equal(D.detect(s,map,opts),0);assert.equal(D.detect(s,map,{...opts,manual:true}),1);assert.equal(D.detect(s,map,{...opts,manual:true}),0);assert.equal(logs.length,1);assert.equal(s.knowledge.hazards['1:pit'].mapped,true)});
test('High Perception detects two tiles ahead, but never through a blocker',()=>{const s=party();s.party[0].perception=16;const m={...map,hazards:[{id:'far',type:'trap',tile:[2,0]}]};assert.equal(D.detect(s,m,{clear:()=>false,notify:()=>{}}),0);assert.equal(D.detect(s,m,{clear:()=>true,notify:()=>{}}),1)});
test('Wrong direction and unconscious observers cannot detect',()=>{const s=party();s.dir=0;assert.equal(D.detect(s,map,{manual:true,clear:()=>true,notify:()=>{}}),0);s.dir=1;s.party[0].hp=0;assert.equal(D.detect(s,map,{manual:true,clear:()=>true,notify:()=>{}}),0)});
test('Fall reveals source before relocation, applies damage, persists through JSON',()=>{const s=party();s.x=1;D.trigger(s,map,{notify:()=>{},relocate:d=>{[s.x,s.y]=d.tile;return true}});assert.equal(s.x,2);assert.equal(s.party[0].hp,18);const saved=JSON.parse(JSON.stringify(s));D.normalize(saved,map);assert.deepEqual(saved.knowledge.hazards['1:pit'].tile,[1,0])});
test('Rotator turns and loses bearings; Lost freezes exploration and preserves history',()=>{const s=party();const m={...map,hazards:[{id:'spin',type:'rotator',tile:[0,0]}]};D.trigger(s,m,{notify:()=>{},random:()=>0});assert.equal(s.dir,2);assert.equal(s.lost,true);s.x=5;D.explore(s,m);assert.equal(s.visited['1:5,0'],undefined);assert.equal(s.visited['1:0,0'],true)});
test('Hazards discovered while Lost are remembered without plotting new coordinates',()=>{const s=party();s.lost=true;D.reveal(s,map.hazards[0],'trigger',()=>{});assert.equal(s.knowledge.hazards['1:pit'].mapped,false);s.lost=false;s.x=1;D.explore(s,map);assert.equal(s.knowledge.hazards['1:pit'].mapped,true)});
test('Only previously known landmarks or validated ability hooks reorient',()=>{const s=party();s.lost=true;s.x=3;s.y=3;assert.equal(D.reorient(s,map),false);s.x=0;s.y=0;assert.equal(D.reorient(s,map),true);s.lost=true;s.x=5;assert.equal(D.reorient(s,map,{ability:true}),true);assert.equal(s.visited['1:5,0'],true)});
test('Normal and reinforced doors migrate closed; special states persist',()=>{const s=party();const doors=[{id:'a',type:'standard_door'},{id:'b',type:'reinforced_door'},{id:'c',type:'standard_door',locked:true}];s.openedDoors={a:true,b:true,c:true};delete s.knowledge;D.normalize(s,{...map,doors});assert.deepEqual(s.openedDoors,{c:true});assert.equal(s.knowledge.doors['1:a'],true);for(const flag of ['locked','sealed','jammed','broken','scripted','requiresInteraction'])assert.equal(D.automaticDoor({type:'standard_door',[flag]:true}),false)});

// Execute the actual game script with a small DOM adapter; no duplicate movement logic.
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
for(const script of scripts)new vm.Script(script);
const elements=new Map();
function element(){return {style:{},children:[],classList:{values:new Set(),add(v){this.values.add(v)},remove(v){this.values.delete(v)},toggle(v,on){if(on)this.values.add(v);else this.values.delete(v)}},appendChild(e){this.children.push(e)},innerHTML:'',textContent:'',parentElement:{clientWidth:100,clientHeight:100},getContext(){return {}},value:'Warrior'}}
const context=vm.createContext({DungeonKnowledge:D,console,Image:class{addEventListener(){}},document:{querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s)},createElement:element},requestAnimationFrame:()=>{},performance:{now:()=>0},setTimeout:()=>{},fetch:()=>new Promise(()=>{}),localStorage:{getItem:()=>null,setItem:()=>{}}});
vm.runInContext(scripts[0],context);
const run=s=>vm.runInContext(s,context);
run(`drawDungeonScene=()=>{};floorMap={width:4,height:2,rows:['####','####'],objects:[{id:'gate',type:'entrance',tile:[0,1]}],doors:[{id:'door',type:'standard_door',between_tiles:[[0,0],[1,0]]}],hazards:[]};doorByEdge=new Map([[edgeKey(0,0,1,0),floorMap.doors[0]]]);state={floor:1,x:0,y:0,dir:1,steps:0,gold:0,party:[{name:'A',cls:'Warrior',hp:20,maxhp:20,mp:0,maxmp:0,level:1,xp:0,perception:16}],inv:[],rooms:{'0,0':{cleared:true},'1,0':{cleared:true},'2,0':{cleared:true}},enemy:null};DungeonKnowledge.normalize(state,floorMap);`);
test('Actual movement passes and closes ordinary doors, preserves both tiles, hides interaction',()=>{run('learnCurrentTile();move()');assert.equal(run('state.x'),1);assert.equal(run('state.openedDoors.door'),undefined);assert.equal(run("state.visited['1:0,0']&&state.visited['1:1,0']"),true);assert.equal(run("state.knowledge.doors['1:door']"),true);assert.equal(html.includes('id="openDoor"'),false);assert.equal(elements.get('#interact').classList.values.has('hidden'),true)});
test('Actual reinforced door traversal works in reverse',()=>{run("floorMap.doors[0].type='reinforced_door';state.dir=3;move()");assert.equal(run('state.x'),0);assert.equal(run('state.openedDoors.door'),undefined)});
test('Locked and scripted doors still block passage and cannot be generically opened',()=>{run('floorMap.doors[0].locked=true;state.dir=1;move();interact()');assert.equal(run('state.x'),0);assert.equal(run('state.openedDoors.door'),undefined);run('floorMap.doors[0].locked=false;floorMap.doors[0].scripted=true;move();interact()');assert.equal(run('state.x'),0);assert.equal(run('state.openedDoors.door'),undefined);run('floorMap.doors[0].scripted=false')});
test('Actual detection respects closed doors',()=>{run("floorMap.hazards=[{id:'hidden',type:'pit',tile:[1,0]}]");assert.equal(run('inspectDirection()'),0);assert.equal(run('inspectDirection(true)'),0)});
test('Actual Lost map hides marker and coordinates; load does not reveal current tile',()=>{run("state.lost=true;state.x=3;state.y=0;render();renderMap()");assert.match(elements.get('#location').textContent,/Lost.*\?\?\?/);assert.match(elements.get('#mapFloor').textContent,/Lost/);assert.equal(elements.get('#dungeonMap').children.some(e=>e.classList.values.has('current')),false);run("findSavedGame=()=>({data:JSON.parse(JSON.stringify(state))});load()");assert.equal(run('state.lost'),true);assert.equal(run("state.visited['1:3,0']"),undefined)});
test('Known hazards remain dangerous without repeating discovery messages',()=>{const s=party();s.x=1;const logs=[];for(let i=0;i<2;i++)D.trigger(s,map,{notify:m=>logs.push(m)});assert.equal(s.party[0].hp,16);assert.equal(logs.filter(m=>m.includes('discover')).length,1)});
test('Loading while Lost never maps a special door opened without bearings',()=>{const s=party();s.lost=true;s.openedDoors.special=true;D.normalize(s,{...map,doors:[{id:'special',type:'gate'}]});assert.equal(s.knowledge.doors['1:special'],undefined)});
test('Actual movement into rotator freezes subsequent exploration and save preserves it',()=>{run("state.lost=false;state.x=0;state.y=0;state.dir=1;state.visited={};floorMap.hazards=[{id:'rotator',type:'rotator',tile:[1,0]}];learnCurrentTile();move()");assert.equal(run('state.lost'),true);run('state.dir=1;move()');assert.equal(run('state.x'),2);assert.equal(run("state.visited['1:2,0']"),undefined);assert.equal(run("state.visited['1:0,0']"),true)});
test('Fountain, entrance and stairs retain contextual actions',()=>{run("state.x=0;state.y=1;state.lost=false;render()");assert.equal(elements.get('#interact').textContent,'EXIT');run("floorMap.objects.push({id:'f',type:'fountain',interaction_tiles:[[2,1]]});state.x=2;render()");assert.equal(elements.get('#interact').textContent,'DRINK');run("floorMap.objects.push({id:'s',type:'stairs_down',tile:[3,1]});state.x=3;render()");assert.equal(elements.get('#interact').textContent,'DESCEND')});
console.log(`${passed} tests passed; both inline scripts compile.`);

